# Generated by Django 3.2.3 on 2021-05-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
